### ISSUE TITLE
'Flatten' utility

### ISSUE THREAD

**Issue by sinlerdev** [vinum-team/Vinum#22]
A way to "flatten" state objects that store an state object (this can go on for x times) would perhaps be useful. 

Though I still haven't thought about it in detail. I am just leaving it here until I finish the huge rewrite I am working on.

**Comment by sinlernick** [comment]
Should we write a "Flattened" State struct or a `flattenRead` operator? Each one could possibly have different uses.

**Comment by sinlernick** [comment]
Deferred to 0.5
